### ISSUE TITLE
使用anchore+Jenkins进行镜像扫描

### ISSUE THREAD

**Issue by zj1244** [zj1244/Blog#15]
## 安装
从Jenkins主菜单中选择Manage Jenkins。
![image](https://user-images.githubusercontent.com/29372171/67746183-eb1f1d00-fa60-11e9-85ca-0fb2a63a1ecb.png)
单击【可选插件】选项卡，然后过滤框里输入【anchore】，然后单击【直接安装】，安装过程中无须选中【安装完成后重启Jenkins(空闲时)】
![image](https://user-images.githubusercontent.com/29372171/67746409-61238400-fa61-11e9-911a-034cbe05d4e6.png)
### anchore插件配置
从【Manage Jenkins】菜单中选择【configure system】，找到【Anchore Container Image Scanner】，按照实际情况填写：

- Engine URL：anchore引擎url地址

- Engine Username：用户名

- Engine Password：密码

![image](https://user-images.githubusercontent.com/29372171/67746755-17876900-fa62-11e9-8a51-4cba2f8ac935.png)

### 添加docker仓库帐号

点击凭据->系统->全局凭据->Add Credentials，添加一个docker  hub的帐号，id填写dockerhub_1。点击【ok】完成添加

![1](https://user-images.githubusercontent.com/29372171/76197110-7e920700-6226-11ea-9990-414db13c5a0b.png)

到此安装配置完成。

## 把Anchore添加到构建过程
可以把anchore添加到pipe line或者freestyle，下面以pipeline为例说明构建过程：
新建一个任务，并选择pipe line，在【流水线】里输入以下脚本后确定，其中bailOnFail=false表示就算存在高危漏洞，构建过程也会标识成成功。bailOnPluginFail=false表示如果anchore服务器连不上，或者扫描插件存在错误，构建过程依然标识成功。需要注意的是，推荐在流水线中把push image动作放在镜像扫描前面：

**好处**：不会因为扫描而影响业务发布（笔者实践中发现虽然扫描会在2分钟之内完成，但是还是有个别开发会抱怨怎么那么慢）
**坏处**：不能阻止有漏洞的镜像发布

```
pipeline {
    environment {
        registry = "lovewin2k/demo"  //仓库地址，默认使用docker hub。按照实际情况修改
        registryCredential = 'dockerhub_1'  //登陆仓库用户名密码，按照实际情况修改
         
    }
     
    agent any
    stages {   
        stage('Cloning Git') {
            steps {
                git 'https://github.com/tahmed11/docker-dvwa.git'
                }
             
        }
        stage('Build Image') {
            steps {
                script {
                    app = docker.build(registry+ ":$BUILD_NUMBER")
                }
            }
        }
        stage('Push Image') {
            steps {
                script {
                    docker.withRegistry('', registryCredential ) {
                        app.push()
                    }
                }
            }
        }
        stage('Container Security Scan') {
            steps {
                 
                sh 'echo "'+registry+':$BUILD_NUMBER `pwd`/Dockerfile" > anchore_images'
                anchore engineRetries: "120", bailOnFail: false, bailOnPluginFail: false, name: 'anchore_images'
                //anchore name: 'anchore_images'
                 
            }
             
        }
        stage('Cleanup') {
             steps {
             sh script: "docker rmi " + registry+ ":$BUILD_NUMBER"
             }
              
        }
 
         
    }
}
```
![image](https://user-images.githubusercontent.com/29372171/67747030-d6dc1f80-fa62-11e9-9be8-fd7229ee80c7.png)

点击【Build now】进行构建，构建完成后可以点击【Anchore Report】查看扫描报告

![image](https://user-images.githubusercontent.com/29372171/67747155-21f63280-fa63-11e9-9a1b-23aff2ceb8a9.png)

该报告显示摘要信息以及扫描结果的详细列表：

![image](https://user-images.githubusercontent.com/29372171/67747204-3a664d00-fa63-11e9-885d-1eefd753aa94.png)

## 参考
https://jenkins.io/doc/pipeline/steps/anchore-container-scanner/
https://dzone.com/articles/anchore-container-image-scanner-jenkins-plugin
https://medium.com/faun/step-by-step-guide-to-integrate-opensource-container-security-scanner-anchore-engine-with-cicd-580da8db5dfc
https://anchore.com/integrating-anchore-scanning-into-jenkins-pipeline-via-jenkinsfile/
https://wiki.jenkins.io/display/JENKINS/Anchore+Container+Image+Scanner+Plugin

**Comment by Aimee-Song** [comment]
我想请教一下，将自己搭建的仓库添加到anchore后，anchore engine会自动扫描添加的镜像吗

**Comment by zj1244** [comment]
你说的添加到anchore后，是用本文的方法加入么？还是其他什么方法？

**Comment by Aimee-Song** [comment]
anchore-cli add registry 方式和调用anchore swagger api POST​/registries方式我都尝试过，添加到anchore后，好像没啥用。他并不会自动扫描我仓库里本来的镜像，或者扫描我现在上传的镜像
