### ISSUE TITLE
我想请教一下，将自己搭建的仓库添加到anchore后，anchore engine会自动扫描添加的镜像吗

### ISSUE THREAD

**Issue by Aimee-Song** [zj1244/Blog#32]
不借助jenkins的话，将仓库添加到anchore，能否自动扫描实时上传的镜像安全

_Originally posted by @Aimee-Song in https://github.com/zj1244/Blog/issues/15#issuecomment-633516286_

**Comment by zj1244** [comment]
确实，好像加入自己的仓库后不会自动扫描.后来我查了查，下面这个插件应该可以实现自动扫描镜像。你可以试试，不过只适用于harbor
https://github.com/anchore/harbor-scanner-adapter
